# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-26 07:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Name',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('birthday', models.DateField()),
                ('gender', models.CharField(choices=[('man', '男'), ('woman', '女'), ('other', '其他')], max_length=1)),
            ],
        ),
    ]
