# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-26 07:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='name',
            old_name='first_name',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='name',
            name='last_name',
        ),
        migrations.AlterField(
            model_name='name',
            name='gender',
            field=models.CharField(choices=[('man', '男'), ('woman', '女'), ('other', '其他')], max_length=20),
        ),
    ]
